

## *Charlottesville 2017 on Twitter, Capstone Project*
##### *Author: Juliette Cook, Student*
##### *Date: 11/26/17*

#### _What is the problem you want to solve?_
  
The problem I want to solve in this project is to decrease the amount of weaponized language on Twitter that has created violence, threats, tension and division on Twitter based on the events leading to protests in Charlottesville in 2017. 
 
    

#### _Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?_

My client are enforcers of the law - cybercrime, forensic enginners that read digital footprints of criminals and their behavior.   
    
Based on the analysis of the intense events in Charlottesville 2017 on twitter, the law enforcement agencies can trace accounts that threaten violence.  
    
They might decide to have an online police presence to prevent further tragedies on social media.   
    
A better understanding of social networks can help law enforcement track down the leaders of violent groups or anyone engaged in criminal activity in a White Nationalist group.
    
    

#### _What data are you going to use for this? How will you acquire this data?_

Kaggle already has millions of tweets, a rather large raw dataset related to the Charlottesville incident. The link to kaggle is here: [Charlottesville on Twitter](https://www.kaggle.com/vincela9/charlottesville-on-twitter ). 
I may also create raw data from the dates right before the Charlottesville incident using Twitter's API.



#### _In brief, outline your approach to solving this problem (knowing that this might change later)._
 
* My approach to solving this problem would start with identifying the accounts that have the larger following, heads of different White Nationalist groups, for example.   
   
* I would want to identify the hashtags associated with the march to promote the event. 
  
* I would also want to know the influencers and amplifiers during this time - those that would be calculated by the number of Retweets.  
    
* Finally, a sentiment analysis based on keywords in conversations that would flag a coordinated effort to increase outrage, build awareness of weaponized information as well as those threatening others with weapons online.

#### _What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck._
 
My deliverables would include R code that would be wrangled and clean. 

There would be 4 different clean sets of code, exploration of data, and plots or graphs to indicate the following:  
    
 1. Account and Group Identification
 
 2. Popular hashtags, time of day, day of the week, exact date before the Charlottesville event.

 3. Largest influencers on Twitter affecting the events of Charlottesville, including Account Names, ID numbers, Most Popular Tweets (highest amount of retweets) socially affected.
 
 4. Sentiment analysis that would show keywords that were widely used to express and represent anger and violence. A colored graph would be helpful to create emotional intensity that caused the actual violence.

